### PR TITLE
Added deprecation notice

### PR DESCRIPTION
**Pull request by niftylettuce**
See https://github.com/ladjs/pre-cache-pug-views which has Koa support as well and does not have circular dependency issue.

This does also not use `app.mount` which is deprecated; your README usage was extremely confusing as well to end users.

Thanks!

### CODE REVIEW

**Comment by antpaw** [comment]
can you please submit your other branch as pull request?

**Comment by niftylettuce** [comment]
@antpaw I can't because that actually does not work.  This package should be deprecated since it's completely sync, doesn't use a storage mechanism, slows down app boot-up speed, and has cyclic dependency error. See <https://github.com/ladjs/cache-pug-templates>?

**Comment by antpaw** [comment]
but what do you do with that module if you don't have redis in your stack? introduce redis just for the sake of caching the pugs?

**Comment by niftylettuce** [comment]
@antpaw what else is in your stack that you could use?  if you use in-memory store it severely degrades performance and prevents your app from booting quickly.

**Comment by niftylettuce** [comment]
Let me know?  FYI the error received using your package on Node v8.x is `TypeError Cyclic __proto__ value`.  I also think binding an `app.mount` is bad practice.  I'd love it if you could refer users to use mine!  Would gladly add additional storage supports for you - just tell me what your alternative is instead of Redis?  File system store?

**Pull request closed without merging**
